### ISSUE TITLE
Segmentation violation in heppy (producing and reading events with different versions of ROOT)

### ISSUE THREAD

**Issue by clementhelsens** [HEP-FCC/FCCSW#149]
The file here /eos/fcc/hh/tutorials/ttbar/ttbar_1.root has been produced with 
source /afs/cern.ch/exp/fcc/sw/0.8pre/setup.sh
so with ROOT 6.06.00.

If you now try to run heppy master with 
source /afs/cern.ch/exp/fcc/sw/0.8pre1/setup.sh
so with 6.08.00
you will have:
*** Break *** segmentation violation

without any further message.

To reproduce the problem:
source /afs/cern.ch/exp/fcc/sw/0.8pre1/setup.sh
git clone https://github.com/HEP-FCC/heppy.git
cd heppy
source ./init.sh
cd test
python analysis_hh_ttbar_cfg.py

**Comment by jlingema** [comment]
I can confirm that the crash occurs, but it doesn't seem to have anything to do with the fact that two different ROOT versions were used to write / read the file.

1) If I run on the file from EOS the segmentation violation occurs
2) If I first copy the file to my local disc / afs, heppy runs through without any problem

Investigating...

**Comment by jlingema** [comment]
Turns out this is a bug in ROOT / xrootd and can easily be reproduced without usage of any FCC software. I created a ticket [here](https://sft.its.cern.ch/jira/browse/ROOT-8508).

**Comment by clementhelsens** [comment]
ok, thanks for the investigation!
