### ISSUE TITLE
Loading libDDEve in pyROOT fails with Error

### ISSUE THREAD

**Issue by vvolkl** [HEP-FCC/FCCSW#158]
Using the  FCCSW v0.8 config file on lxplus, it is possible to load libDDEve from  ROOT (`root [0] gSystem->Load("libDDEve")`) but not from pyROOT, which affects the Visualization package:

```
~$ ./run python Visualization/python/eventDisplay.py 
cling::DynamicLibraryManager::loadLibrary(): dlopen: cannot load any more object with static TLS
Traceback (most recent call last):
  File "Visualization/python/eventDisplay.py", line 6, in <module>
    assert -1 != ROOT.gSystem.Load("libDDEve"), "Could not load the Eve library! Check that libDDEve.so is in your path."
AssertionError: Could not load the Eve library! Check that libDDEve.so is in your path.
``` 

This issue might be fixed with the new release or with switching the script from python to a root macro.

**Comment by andresailer** [comment]
Can you try adding
```  
  orgLevel = ROOT.gErrorIgnoreLevel
  ROOT.gErrorIgnoreLevel=6000
  gSystem.Load("libglapi")
  ROOT.gErrorIgnoreLevel=orgLevel
```
before loading libDDEve? This works in DDG4: 
https://github.com/AIDASoft/DD4hep/blob/master/DDG4/python/DDG4.py#L20

**Comment by vvolkl** [comment]
Ah, this solves the problem on lxplus without X! When using X-forwarding the problem is still there, but I found I just have to preload another library:
```
ROOT.gSystem.Load("libQtOpenGL")
```
Many Thanks.
