### ISSUE TITLE
Problem using particles in SimG4SingleParticleGeneratorTool

### ISSUE THREAD

**Issue by jhrdinka** [HEP-FCC/FCCSW#251]
When handing over another particle name than "geantino" to the SimG4SingleParticleGeneratorTool the initialisation of the tool fails [here](https://github.com/HEP-FCC/FCCSW/blob/master/Sim/SimG4Components/src/SimG4SingleParticleGeneratorTool.cpp#L41) because the particle is not found.

**Comment by vvolkl** [comment]
I think I figured out why it isn't working for you - can you check that you indeed used the right physics list? The G4ParticleTable is defined in the physics list, and `SimG4GeantinoDeposits` doesn't know about muons. If that's the case, please change it to `SimG4FtfpBert`.

**Comment by jhrdinka** [comment]
Yes, I used the right physics list. However I just found the problem. It is not in the `SimG4SingleParticleGeneratorTool`, but in the `geant_fullsim_pgun_geantino.py` - example. One needs to use the `Gaudi__ParticlePropertySvc` and use the particle properties file: "Generation/data/ParticleTable.txt".

**Comment by vvolkl** [comment]
I'm a bit surprised, because the `SimG4SingleParticleGeneratorTool` is not using the ParticlePropertyService, only the `MomentumRangeParticleGun`, but in any case, if it works you can close the issue.
