### ISSUE TITLE
Use Gaudi ToolHandleArrays instead of lists of strings 

### ISSUE THREAD

**Issue by vvolkl** [HEP-FCC/FCCSW#361]
As noted in comments in the code (https://github.com/HEP-FCC/FCCSW/blob/master/Sim/SimG4Components/src/SimG4Alg.h#L63), the proper mechanism to have several tools of the same type would be the ToolHandleArray, which was not working at the time this component was implemented. I followed up with Gaudi, and the issue is under active development now: https://gitlab.cern.ch/gaudi/Gaudi/issues/83

**Comment by kjvbrt** [comment]
Implemented in: https://github.com/HEP-FCC/k4SimGeant4/pull/53
