### ISSUE TITLE
dd4hep issue under zsh

### ISSUE THREAD

**Issue by ajbhiggs** [HEP-FCC/FCCSW#40]
I seem not to be able to run the setup scrips under zsh, as follows:

barra/FCCSW% source init.sh
Gaudi   :    /data/atlas/atlasdata/barra/FCCSW/GAUDI/GAUDI_v25r2
FCC root:    /data/atlas/atlasdata/barra/FCCSW
FCCEDM  :    /afs/cern.ch/exp/fcc/sw/0.3/fcc-edm/0.1/x86_64-slc6-gcc48-opt
ALBERS  :    /afs/cern.ch/exp/fcc/sw/0.3/albers/0.1/x86_64-slc6-gcc48-opt
ERROR: must cd where/dd4hep/is before calling . bin/thisdd4hep.sh for this version of bash!

**Comment by clementhelsens** [comment]
hello,

yes, you should use bash shell.
if you have any other question, please use the FCC-SW mailing list

fcc-experiments-sw-dev@cern.ch<mailto:fcc-experiments-sw-dev@cern.ch>

Cheers,
Clement

Le 22 oct. 2015 à 18:50, ajbhiggs <notifications@github.com<mailto:notifications@github.com>> a écrit :


I seem not to be able to run the setup scrips under zsh, as follows:

barra/FCCSW% source init.sh
Gaudi : /data/atlas/atlasdata/barra/FCCSW/GAUDI/GAUDI_v25r2
FCC root: /data/atlas/atlasdata/barra/FCCSW
FCCEDM : /afs/cern.ch/exp/fcc/sw/0.3/fcc-edm/0.1/x86_64-slc6-gcc48-opt<http://cern.ch/exp/fcc/sw/0.3/fcc-edm/0.1/x86_64-slc6-gcc48-opt>
ALBERS : /afs/cern.ch/exp/fcc/sw/0.3/albers/0.1/x86_64-slc6-gcc48-opt<http://cern.ch/exp/fcc/sw/0.3/albers/0.1/x86_64-slc6-gcc48-opt>
ERROR: must cd where/dd4hep/is before calling . bin/thisdd4hep.sh for this version of bash!

**Comment by hegner** [comment]
I fixed this init.sh and a few scripts downstream. They should work w/ zsh now. Please pull again from the repository.
