### ISSUE TITLE
Unit Issue in HEPMC

### ISSUE THREAD

**Issue by vvolkl** [HEP-FCC/FCCSW#418]
When converting from hepmc to edm4hep, the code correctly checks if HEPMC uses GeV or MeV. However, the particle guns will always assume that HEPMC uses MeV and there will be a discrepancy if HEPMC is compiled with `-Dmomentum=GeV`.

This was never an issue when using the lcg releases, but came to light because in the spack installation the HEPMC units were different.

**Comment by andresailer** [comment]
That could be making the tests taking longer (https://github.com/HEP-FCC/FCCSW/issues/418) if the energy is 1000 times higher?

**Comment by vvolkl** [comment]
I only realize this now, but it would explain perfectly this rather strange problem. Thanks a lot, will check this now!

**Comment by vvolkl** [comment]
That was indeed the case. Fixed by #419
